# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8431b1f1f1bf04a850ae8cf68ccc0123b8013efd19b2832c378bdb20fdd48689672475d08f40f814d0a2a4dfe83f1eedf07cf8ba844576e17d0c22c1ee77ebb

test:
  secret_key_base: 931b17424feaa1819d1aac8897468ecba199e567493b24598be0d0b9e83d22ce83150fa5339aa69623738afcdf66279227b23ca0235bd3ce31a3e0811f561419

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
