# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1ecccc4006b43792eda3b08b8edc5e919f94772ccaea66bfa823dd76ca871e4cfb0510863e3c4926fdc0f9a7dff68dc4fbfc99bb2dd621127ceea30108f5b36

test:
  secret_key_base: f12bc015844d36eee9d46f884a1fa7333993944609322818c16fbeab85e431ff816be03b5b16353aa3dd579ff98a6d1e54c27db105046875ccc740d26fe592fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
